base_url = "https://blog.fnil.net"
title = "Think and Act as One"
description = "CEO & Founder of Greptime. Writing about systems, distributed computing, AI & Programming."
author = "Dennis Zhuang"
generate_feeds = true
compile_sass = true
minify_html = true
build_search_index = true

default_language = "en"
theme = "tabi"

taxonomies = [{name = "tags", feed = true}]

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
bottom_footnotes = true
smart_punctuation = true

[markdown.highlighting]
theme = "catppuccin-frappe"

[extra]
theme_switcher = true
default_theme = ""
skin = ""

show_reading_time = true
show_date = true
copy_button = true
toc = true

menu = [
    { name = "archive", url = "archive", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
]

favicon = "img/favicon.png"

stylesheets = ["custom.css"]

socials = [
    { name = "github", url = "https://github.com/killme2008", icon = "github" },
    { name = "linkedin", url = "https://www.linkedin.com/in/dennis-zhuang/", icon = "linkedin" },
    { name = "x", url = "https://x.com/killme20082", icon = "twitter" },
]
