base_url = "https://blog.fnil.net"
title = "fnil's blog"
description = "Personal blog"
author = "fnil"
generate_feeds = true
compile_sass = true
minify_html = true
build_search_index = true

default_language = "zh"

taxonomies = [{name = "tags", feed = true}]

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
bottom_footnotes = true
smart_punctuation = true

[markdown.highlighting]
theme = "catppuccin-frappe"
style = "class"

[extra]
theme = "tabi"
theme_switcher = true
default_theme = ""
skin = "teal"

show_reading_time = true
show_date = true
copy_button = true
toc = true

menu = [
    { name = "blog", url = "blog", trailing_slash = true },
    { name = "archive", url = "archive", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
]

favicon_emoji = "üìù"

socials = [
    { name = "github", url = "https://github.com/killme2008", icon = "github" },
]
